version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    command:
      - start-dev
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - ./config/keycloak-realm.json:/opt/keycloak/data/import/realm.json

  netbird:
    image: netbirdio/netbird:latest
    depends_on:
      - keycloak
    ports:
      - "3000:3000"
    environment:
      NETBIRD_DOMAIN: ${NETBIRD_DOMAIN}
      OIDC_PROVIDER: http://${HOST_IP}:8080/realms/netbird
    command: ["netbird-server"]

  opa:
    image: openpolicyagent/opa:latest
    ports:
      - "8181:8181"
    command:
      - "run"
      - "--server"
      - "/policies/opa-policy.rego"
    volumes:
      - ./config/opa-policy.rego:/policies/opa-policy.rego

  squid:
    image: sameersbn/squid:latest
    ports:
      - "3128:3128"
    volumes:
      - ./config/squid.conf:/etc/squid/squid.conf

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.1
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - ./config/grafana:/etc/grafana

volumes:
  esdata:

